name: CMake

on: [push]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: RelWithDebInfo

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Install Miniconda
      - name: Install Miniconda
        run: |
          wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
          bash miniconda.sh -b -p $HOME/miniconda
          source $HOME/miniconda/etc/profile.d/conda.sh

      # Install mamba
      - name: Install mamba
        run: conda install mamba -n base -c conda-forge -y

      # Create Conda environment
      - name: Create Conda environment
        run: conda create --name vegetation python=3.10 -y

      # Activate Conda environment
      - name: Activate Conda environment
        run: source $HOME/miniconda/bin/activate vegetation

      # Install dependencies using mamba
      - name: Install dependencies
        run: pip install -r requirements.txt

      # Print Python version for debugging
      - name: Check Python version
        run: python --version

      # List directory contents for debugging
      - name: List directory contents
        run: ls -la

      # Configure CMake
      - name: Configure CMake
        run: cmake --preset default

      # Build
      - name: Build
        run: cmake --build --preset default

      # Test
      - name: Test
        run: ctest --preset default
