name: CMake

on: [push]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: RelWithDebInfo

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Install Miniforge
      - name: Install Miniforge
        run: |
          wget https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-Linux-x86_64.sh -O miniforge.sh
          bash miniforge.sh -b -p $HOME/miniforge3
          source $HOME/miniforge3/bin/activate

      # Install mamba
      - name: Install mamba
        run: conda install mamba -n base -c conda-forge -y

      # Create Conda environment
      - name: Create Conda environment
        run: conda create --name vegetation python=3.10 -y

      # Activate Conda environment
      - name: Activate Conda environment
        run: source $HOME/miniforge3/bin/activate vegetation

      # Install dependencies using mamba
      - name: Install dependencies
        run: pip install -r requirements.txt

      # Print Python version for debugging
      - name: Check Python version
        run: python --version

      # List directory contents for debugging
      - name: List directory contents
        run: ls -la

      # Configure CMake
      - name: Configure CMake
        run: cmake --preset default

      # Build
      - name: Build
        run: cmake --build --preset default

      # Test
      - name: Test
        run: ctest --preset default
