name: C/C++ CI

on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            cmake \
            git \
            libmpfr-dev \
            libboost-dev \
            libcurl4-openssl-dev \
            libcgal-dev \
            libfmt-dev

      - name: Clone CGAL master branch
        run: |
          git clone --branch master https://github.com/CGAL/cgal.git
          cd cgal
          mkdir cgal.install
          cd cgal.install
          cmake -DCMAKE_INSTALL_PREFIX=$GITHUB_WORKSPACE/cgal.install ..
          make install

      - name: Configure project
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_PREFIX_PATH=$GITHUB_WORKSPACE/cgal.install ..

      - name: Build project
        run: |
          cd build
          cmake --build . -- -j2  # Adjust the number of parallel jobs
