name: C/C++ CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y \
          libboost-all-dev \
          libmpfr-dev \
          libgmp-dev \
          libcurl4-openssl-dev \

      - name: Clone CGAL master branch
        run: git clone --branch master https://github.com/CGAL/cgal.git

      - name: Configure and build
        run: |
          mkdir build
          cd build
          cmake -DCGAL_DIR=$GITHUB_WORKSPACE/CGAL-5.6.1 -DCMAKE_BUILD_TYPE=Release ..
          cmake --build .

      - name: Run tests
        run: |
          cd build
          ctest --output-on-failure
