name: C/C++ CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install libcgal-dev libfmt-dev libspdlog-dev libmpfr-dev libboost-all-dev libcurl4-openssl-dev

      - name: Cmake
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: |
          cd build
          make

      - name: Test
        run: |
          cd build
          ctest --output-on-failure
