name: C/C++ CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: sudo apt-get install libcurl4-openssl-dev libjsoncpp-dev

    - name: Configure CMake
      run: |
        mkdir build
        cd build
        cmake ..
        
    - name: Build
      run: |
        cd build
        make

    - name: Test
      run: |
        cd build
        ctest