name: C/C++ CI

on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            cmake \
            git \
            libmpfr-dev \
            libboost-dev \
            libcurl4-openssl-dev \
            libcgal-dev \
            libfmt-dev

      - name: Clone CGAL master branch
        run: |
          git clone --branch master https://github.com/CGAL/cgal.git
          -CDMAKE_INSTALL_PREFIX=$GITHUB_WORKSPACE/cgal.install ./cgal
          make install

      - name: Configure and build
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_PREFIX_PATH=$GITHUB_WORKSPACE/cgal.install ..
          cmake --build .

      - name: Run tests
        run: |
          cd build
          ctest --output-on-failure
