name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Github Action for LaTeX
        uses: xu-cheng/latex-action@3.1.0

        with:
          root_file: |
            report.tex
            intro.tex

      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: PDF
          path: |
            report.pdf
            intro.pdf
