name: Build LaTeX document
on: [pull_request]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4

      - name: List report directory contents
        run: ls -R report

      - name: List report/images directory contents
        run: ls -R report/images

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: report/report.tex
